//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norman_Manley_Institution_for_the_Impaired
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string StaffPosition { get; set; }
        public string StaffPassword { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
    }
}
